on:
<<<<<<< HEAD
  push:
  pull_request_target:
    branches: [master]
=======
>>>>>>> 274eb3f4208f68c193d8e8856fb2f4f44edfbd80
  push:
  pull_request_target:
    branches: [master]
name: Tests / test-user-mirror
jobs:
<<<<<<< HEAD
  runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        uses: Yikun/hub-mirror-action@master
        with:
          # 必选，需要同步的 Github 用户（源）
          src: 'github/${{ github.repository_owner }}'
          # 必选，需要同步到的 Gitee 用户（目的）
          dst: 'gitee/smallfawn'
          # 必选，Gitee公钥对应的私钥，https://gitee.com/profile/sshkeys
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          # 必选，Gitee对应的用于创建仓库的token，https://gitee.com/profile/personal_access_tokens
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          # 如果是组织，指定组织即可，默认为用户 user
          # account_type: org
          # 直接取当前项目的仓库名
          static_list: ${{ github.event.repository.name }}
          # 还有黑、白名单，静态名单机制，可以用于更新某些指定库
          # static_list: 'repo_name,repo_name2'
          # black_list: 'repo_name,repo_name2'
          # white_list: 'repo_name,repo_name2'
=======
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1
    - name: Mirror Github to Gitee with white list
      uses: ./.
      with:
        src: github/smallfawn
        dst: gitee/smallfawn
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: 'Note'
        force_update: true
        debug: true
        mappings: 'hashes=>hashes_gitee'
>>>>>>> 274eb3f4208f68c193d8e8856fb2f4f44edfbd80
