on:
  push:
    branches: [main]
name: update
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: update to gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitee/smallfawn'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: ${{ github.event.repository.name }}
      - name: update to gitlab
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitlab/smallfawn'
          dst_token: ${{ secrets.GITLAB_TOKEN }}
          static_list: ${{ github.event.repository.name }}
          account_type: user
          clone_style: https
          force_update: true
          debug: true