on:
  push:
    branches: [main]
name: gitee - update
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitee/smallfawn'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: ${{ github.event.repository.name }}