on:
  push:
    branches: [master]
  pull_request_target:
    branches: [master]
name: Tests / test-user-mirror
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Mirror repository
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/${{ github.repository_owner }}'
          dst: 'gitee/smallfawn'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: ${{ github.event.repository.name }}
